# docker-compose.https.yml
version: '3.8'

services:
  backend:
    build:
      context: ./AsyncProgrammingAPI
      dockerfile: Dockerfile
    container_name: asyncprogramming-api-https
    ports:
      - "5096:5001"  # HTTPS port
      - "5095:5000"  # HTTP port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123
    volumes:
      # Skopiuj certyfikat developmentu
      - ~/.aspnet/https:/app:ro
    networks:
      - app-network

  frontend:
    build:
      context: ./interactive-learning
      dockerfile: Dockerfile
    container_name: interactive-learning
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://localhost:5096
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
