# docker-compose.yml (w katalogu InteractiveLearning)
version: '3.8'

services:
  backend:
    build:
      context: ./AsyncProgrammingAPI
      dockerfile: Dockerfile
    container_name: asyncprogramming-api
    ports:
      - "5096:5096"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5096;https://+:5001
      - ASPNETCORE_HTTPS_PORT=5001
      # Zezwól na niezaufane certyfikaty w developmencie
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123
    volumes:
      # Montuj certyfikat developmentu
      - ~/.aspnet/https:/https:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./interactive-learning
      dockerfile: Dockerfile
    container_name: interactive-learning
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5096
      - WATCHPACK_POLLING=true
    volumes:
      # Montuj kod dla hot reload (opcjonalnie)
      - ./interactive-learning/src:/app/src
      - ./interactive-learning/public:/app/public
    networks:
      - app-network
    depends_on:
      - backend
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  https-certs:
